# Generated by Django 5.2.17 on 2026-08-27 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('csv', 'CSV export')], default='csv', max_length=16)),
                ('system_key', models.SlugField(help_text='Immutable owner-defined namespace. Not a vendor claim.', max_length=64)),
                ('domain', models.CharField(choices=[('contracts', 'Contracts and scope'), ('identity_crosswalk', 'Identity crosswalk'), ('workers', 'Workers and eligibility'), ('schedule', 'Scheduled shifts'), ('time', 'Time entries'), ('service_events', 'Work orders and service events'), ('invoice_status', 'Accounting invoice status')], max_length=32)),
                ('expected_cadence_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age_minutes', models.PositiveIntegerField(blank=True, help_text='Beyond this age the source is stale and time-sensitive detection is suppressed.', null=True)),
                ('is_authoritative', models.BooleanField(default=False, help_text='Authoritative for its declared fields only.')),
                ('last_successful_import_at', models.DateTimeField(blank=True, null=True)),
                ('last_source_as_of_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_data_source',
                'ordering': ['system_key'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEntityReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('site', 'Site'), ('contract', 'Contract'), ('service_obligation', 'Service obligation'), ('work_order', 'Work order'), ('accounting_invoice', 'Accounting invoice'), ('accounting_payment', 'Accounting payment')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('mapping_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('unresolved', 'Unresolved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='unresolved', max_length=16)),
                ('match_method', models.CharField(blank=True, choices=[('partner_canonical_key', 'Partner canonical key'), ('manual', 'Manually confirmed'), ('deterministic_exact', 'Deterministic exact match')], max_length=32)),
                ('mapping_provenance', models.CharField(blank=True, help_text='Source file/batch/row or named user.', max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_external_entity_reference',
                'ordering': ['entity_type', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='IdentityResolutionIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('site', 'Site'), ('contract', 'Contract'), ('service_obligation', 'Service obligation'), ('work_order', 'Work order'), ('accounting_invoice', 'Accounting invoice'), ('accounting_payment', 'Accounting payment')], max_length=32)),
                ('supplied_external_id', models.CharField(max_length=128)),
                ('reason_code', models.CharField(choices=[('unresolved_identity', 'No candidate found'), ('ambiguous_identity', 'More than one candidate'), ('conflicting_crosswalk', 'Conflicting crosswalk rows'), ('cross_tenant_reference', 'Reference crosses tenants')], max_length=32)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='unresolved', max_length=16)),
                ('candidate_reference_ids', models.JSONField(blank=True, default=list, help_text='Canonical UUIDs considered. Deterministic only.')),
                ('explanation', models.TextField(blank=True, help_text='Safe explanation. Never a raw row.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'ingestion_identity_resolution_issue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_group', models.CharField(choices=[('identity', 'Identity'), ('schedule_status', 'Schedule status'), ('completion', 'Completion'), ('contract_rate', 'Contract and rate'), ('invoice_status', 'Invoice status')], max_length=32)),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('site', 'Site'), ('contract', 'Contract'), ('service_obligation', 'Service obligation'), ('work_order', 'Work order'), ('accounting_invoice', 'Accounting invoice'), ('accounting_payment', 'Accounting payment')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('is_blocking', models.BooleanField(default=True, help_text='A blocking issue prevents dependent detection and financial approval.')),
                ('explanation', models.TextField(help_text='Safe explanation. Never a whole source record.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_reconciliation_issue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcePrecedenceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(help_text='1 is highest precedence.')),
            ],
            options={
                'db_table': 'ingestion_source_precedence_entry',
                'ordering': ['rule', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='SourcePrecedenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('site', 'Site'), ('contract', 'Contract'), ('service_obligation', 'Service obligation'), ('work_order', 'Work order'), ('accounting_invoice', 'Accounting invoice'), ('accounting_payment', 'Accounting payment')], max_length=32)),
                ('field_group', models.CharField(choices=[('identity', 'Identity'), ('schedule_status', 'Schedule status'), ('completion', 'Completion'), ('contract_rate', 'Contract and rate'), ('invoice_status', 'Invoice status')], max_length=32)),
                ('conflict_policy', models.CharField(choices=[('block_and_review', 'Block and require review'), ('prefer_authoritative', 'Prefer the authoritative source'), ('latest_within_authoritative_source', 'Latest within the authoritative source')], max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'ingestion_source_precedence_rule',
                'ordering': ['entity_type', 'field_group', '-effective_from'],
            },
        ),
    ]
