# Generated by Django 5.2.17 on 2026-08-27 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('operations', '0001_initial'),
        ('organizations', '0002_organization_membership_membershiprolegrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='accounting_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='operations.accountinginvoice'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='accounting_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='operations.accountingpayment'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='operations.contract'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='operations.customeraccount'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='service_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='operations.serviceobligation'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='operations.site'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_references', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='ingestion.externalentityreference'),
        ),
        migrations.AddField(
            model_name='externalentityreference',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='operations.workorder'),
        ),
        migrations.AddField(
            model_name='identityresolutionissue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='identityresolutionissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_issues_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityresolutionissue',
            name='resolved_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_issues', to='ingestion.externalentityreference'),
        ),
        migrations.AddField(
            model_name='identityresolutionissue',
            name='supplied_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_issues', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='accounting_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='operations.accountinginvoice'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='accounting_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='operations.accountingpayment'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='chosen_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_resolutions', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='operations.contract'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='operations.customeraccount'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='service_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='operations.serviceobligation'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='operations.site'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='operations.workorder'),
        ),
        migrations.AddField(
            model_name='sourceprecedenceentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='sourceprecedenceentry',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precedence_entries', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='sourceprecedencerule',
            name='authoritative_sources',
            field=models.ManyToManyField(related_name='precedence_rules', through='ingestion.SourcePrecedenceEntry', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='sourceprecedencerule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precedence_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourceprecedencerule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='sourceprecedenceentry',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ingestion.sourceprecedencerule'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('organization', 'system_key'), name='uniq_source_key_per_org'),
        ),
        migrations.AddIndex(
            model_name='externalentityreference',
            index=models.Index(fields=['organization', 'entity_type', 'mapping_status'], name='idx_ext_ref_org_type_status'),
        ),
        migrations.AddConstraint(
            model_name='externalentityreference',
            constraint=models.UniqueConstraint(condition=models.Q(('mapping_status', 'superseded'), _negated=True), fields=('organization', 'source', 'entity_type', 'external_id'), name='uniq_current_external_reference'),
        ),
        migrations.AddConstraint(
            model_name='externalentityreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mapping_status', 'confirmed'), models.Q(models.Q(('customer__isnull', False), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('site__isnull', False), ('customer__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('contract__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('service_obligation__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('work_order__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('accounting_invoice__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_payment__isnull', True)), models.Q(('accounting_payment__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True)), _connector='OR')), models.Q(('mapping_status__in', ['unresolved', 'rejected']), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('mapping_status', 'superseded'), models.Q(models.Q(('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('customer__isnull', False), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('site__isnull', False), ('customer__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('contract__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('service_obligation__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('work_order__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('accounting_invoice__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_payment__isnull', True)), models.Q(('accounting_payment__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True)), _connector='OR')), _connector='OR'), name='ck_external_reference_typed_target'),
        ),
        migrations.AddConstraint(
            model_name='externalentityreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mapping_status', 'confirmed'), _negated=True), models.Q(('confirmed_at__isnull', False), models.Q(('match_method', ''), _negated=True)), _connector='OR'), name='ck_confirmed_reference_has_provenance'),
        ),
        migrations.AddConstraint(
            model_name='identityresolutionissue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'unresolved')), fields=('organization', 'supplied_source', 'entity_type', 'supplied_external_id'), name='uniq_open_identity_issue'),
        ),
        migrations.AddConstraint(
            model_name='identityresolutionissue',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'unresolved'), models.Q(('resolved_by__isnull', False), ('resolved_at__isnull', False)), _connector='OR'), name='ck_identity_issue_resolution_attributed'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('site__isnull', False), ('customer__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('contract__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('service_obligation__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('work_order__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('accounting_invoice__isnull', True), ('accounting_payment__isnull', True)), models.Q(('accounting_invoice__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_payment__isnull', True)), models.Q(('accounting_payment__isnull', False), ('customer__isnull', True), ('site__isnull', True), ('contract__isnull', True), ('service_obligation__isnull', True), ('work_order__isnull', True), ('accounting_invoice__isnull', True)), _connector='OR'), name='ck_reconciliation_issue_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationissue',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'open'), models.Q(('resolved_by__isnull', False), ('resolved_at__isnull', False)), _connector='OR'), name='ck_reconciliation_resolution_attributed'),
        ),
        migrations.AddConstraint(
            model_name='sourceprecedencerule',
            constraint=models.UniqueConstraint(fields=('organization', 'entity_type', 'field_group', 'effective_from'), name='uniq_precedence_rule_effective'),
        ),
        migrations.AddConstraint(
            model_name='sourceprecedencerule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_precedence_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='sourceprecedenceentry',
            constraint=models.UniqueConstraint(fields=('rule', 'source'), name='uniq_precedence_rule_source'),
        ),
        migrations.AddConstraint(
            model_name='sourceprecedenceentry',
            constraint=models.UniqueConstraint(fields=('rule', 'rank'), name='uniq_precedence_rule_rank'),
        ),
        migrations.AddConstraint(
            model_name='sourceprecedenceentry',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='ck_precedence_rank_positive'),
        ),
    ]
