# Generated by Django 5.2.17 on 2026-08-27 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
        ('operations', '0002_initial'),
        ('organizations', '0002_organization_membership_membershiprolegrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sites_contracts', 'Sites and contracts'), ('entity_crosswalk', 'Entity crosswalk'), ('workers_eligibility', 'Workers and eligibility'), ('scheduled_shifts', 'Scheduled shifts'), ('time_entries', 'Time entries'), ('work_orders_service_events', 'Work orders and service events'), ('invoice_status', 'Invoice status')], max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('invalid', 'Invalid'), ('ready', 'Ready to commit'), ('committing', 'Committing'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('original_filename', models.CharField(help_text='Sanitized basename only; never a path.', max_length=255)),
                ('content_sha256', models.CharField(max_length=64)),
                ('mapping_version', models.PositiveIntegerField(default=1)),
                ('source_as_of_at', models.DateTimeField(help_text='When the source system produced this export.')),
                ('observation_mode', models.CharField(choices=[('full_snapshot', 'Full snapshot'), ('bounded_snapshot', 'Bounded snapshot'), ('delta', 'Delta')], max_length=24)),
                ('source_watermark', models.CharField(blank=True, help_text='Opaque non-secret source cursor used only for ordering and replay explanation.', max_length=200)),
                ('coverage_manifest_sha256', models.CharField(help_text='Hash of the normalized coverage declarations.', max_length=64)),
                ('total_row_count', models.PositiveIntegerField(default=0)),
                ('valid_row_count', models.PositiveIntegerField(default=0)),
                ('invalid_row_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_summary', models.CharField(blank=True, help_text='Safe summary. Never a raw row or stack trace.', max_length=500)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches_committed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='ingestion.datasource')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingestion_import_batch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='identityresolutionissue',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_issues', to='ingestion.importbatch'),
        ),
        migrations.CreateModel(
            name='ImportCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_family', models.CharField(max_length=64)),
                ('scope_type', models.CharField(choices=[('organization', 'Whole organization'), ('customer', 'One customer'), ('site', 'One site'), ('worker', 'One worker'), ('work_order', 'One work order'), ('source_ledger', "The batch's own source ledger")], max_length=24)),
                ('coverage_start_at', models.DateTimeField()),
                ('coverage_end_at', models.DateTimeField()),
                ('query_contract_code', models.CharField(choices=[('SCHEDULE_OVERLAP_V1', 'Schedule overlap v1'), ('TIME_ENTRY_OVERLAP_V1', 'Time entry overlap v1'), ('WORKER_AVAILABILITY_OVERLAP_V1', 'Worker availability overlap v1'), ('SERVICE_EVENT_CURRENT_STATE_V1', 'Service event current state v1'), ('ACCOUNTING_SERVICE_DATE_LEDGER_V1', 'Accounting service-date ledger v1')], max_length=48)),
                ('query_contract_version', models.PositiveIntegerField(default=1)),
                ('completeness', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('unknown', 'Unknown')], max_length=16)),
                ('declaration_basis', models.CharField(choices=[('source_export_manifest', 'Source export manifest'), ('partner_attestation', 'Partner attestation'), ('synthetic_fixture', 'Synthetic fixture')], max_length=32)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coverage_declarations', to='operations.customeraccount')),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_declarations', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_declarations', to='ingestion.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coverage_declarations', to='operations.site')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coverage_declarations', to='operations.workorder')),
            ],
            options={
                'db_table': 'ingestion_import_coverage',
                'ordering': ['record_family', 'coverage_start_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(help_text='One-based, matching the source file.')),
                ('raw_data', models.JSONField(help_text='Parsed key/value pairs. Never logged or exported.')),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('committed', 'Committed'), ('unchanged', 'Unchanged')], max_length=16)),
                ('error_codes', models.JSONField(blank=True, default=list)),
                ('target_model', models.CharField(blank=True, max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'ingestion_import_row',
                'ordering': ['import_batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_key', models.CharField(max_length=128)),
                ('as_of', models.DateTimeField()),
                ('input_manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting_inputs', 'Waiting for inputs'), ('ready', 'Ready'), ('enqueued', 'Enqueued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('became_ready_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'ingestion_reconciliation_run',
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRunInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('contracts', 'Contracts and scope'), ('identity_crosswalk', 'Identity crosswalk'), ('workers', 'Workers and eligibility'), ('schedule', 'Scheduled shifts'), ('time', 'Time entries'), ('service_events', 'Work orders and service events'), ('invoice_status', 'Accounting invoice status')], max_length=32)),
                ('accepted_watermark', models.CharField(blank=True, max_length=200)),
                ('coverage_declarations', models.ManyToManyField(blank=True, related_name='reconciliation_inputs', to='ingestion.importcoverage')),
                ('import_batch', models.ForeignKey(blank=True, help_text='Null while the run is still waiting for this domain.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_inputs', to='ingestion.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='ingestion.reconciliationrun')),
            ],
            options={
                'db_table': 'ingestion_reconciliation_run_input',
                'ordering': ['reconciliation_run', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecordVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(max_length=48)),
                ('external_id', models.CharField(max_length=128)),
                ('version_hash', models.CharField(max_length=64)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_data', models.JSONField(help_text='Minimum normalized snapshot required to reproduce a detector decision.')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_versions', to='ingestion.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_versions', to='ingestion.datasource')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='ingestion.sourcerecordversion')),
            ],
            options={
                'db_table': 'ingestion_source_record_version',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='identityresolutionissue',
            name='source_record_version',
            field=models.ForeignKey(blank=True, help_text='Null when the row failed validation before a version was written.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_issues', to='ingestion.sourcerecordversion'),
        ),
        migrations.AddField(
            model_name='reconciliationissue',
            name='conflicting_source_versions',
            field=models.ManyToManyField(blank=True, related_name='reconciliation_issues', to='ingestion.sourcerecordversion'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['organization', 'kind', '-uploaded_at'], name='idx_batch_org_kind'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'source', 'kind', 'content_sha256', 'mapping_version', 'source_as_of_at', 'coverage_manifest_sha256'), name='uniq_import_batch_observation'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'committed'), _negated=True), ('committed_at__isnull', False), _connector='OR'), name='ck_import_batch_committed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='importcoverage',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_end_at__gt', models.F('coverage_start_at'))), name='ck_coverage_interval_ordered'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'row_number'), name='uniq_import_row_number'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gte', 1)), name='ck_import_row_one_based'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.UniqueConstraint(fields=('organization', 'run_key'), name='uniq_reconciliation_run_key'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), ('became_ready_at__isnull', False), _connector='OR'), name='ck_reconciliation_ready_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationruninput',
            constraint=models.UniqueConstraint(fields=('reconciliation_run', 'domain'), name='uniq_run_input_domain'),
        ),
        migrations.AddIndex(
            model_name='sourcerecordversion',
            index=models.Index(fields=['organization', 'record_type', 'external_id'], name='idx_srv_org_type_extid'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecordversion',
            constraint=models.UniqueConstraint(fields=('organization', 'source', 'record_type', 'external_id', 'version_hash'), name='uniq_source_record_version'),
        ),
    ]
