# Generated by Django 5.2.17 on 2026-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptioncase',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
