# Generated by Django 5.2.17 on 2026-08-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0002_exceptioncase_service_date'),
        ('operations', '0002_initial'),
        ('organizations', '0002_organization_membership_membershiprolegrant_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exceptioncase',
            constraint=models.UniqueConstraint(condition=models.Q(('work_order__isnull', False), ('service_date__isnull', False)), fields=('organization', 'exception_type', 'work_order', 'service_date'), name='uniq_case_per_work_order_occurrence'),
        ),
    ]
