# Generated by Django 5.2.17 on 2026-08-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0003_exceptioncase_uniq_case_per_work_order_occurrence'),
        ('organizations', '0002_organization_membership_membershiprolegrant_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financialimpactsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('basis', 'manual_amount_required'), _negated=True), ('invoice_ready_value__isnull', True), _connector='OR'), name='ck_snapshot_manual_basis_has_no_ready_value'),
        ),
    ]
