# Generated by Django 5.2.17 on 2026-08-28 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exceptions', '0003_exceptioncase_uniq_case_per_work_order_occurrence'),
        ('operations', '0002_initial'),
        ('organizations', '0002_organization_membership_membershiprolegrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_type', models.CharField(choices=[('invoice_ready', 'Invoice-ready value'), ('finance_export', 'Finance export'), ('case_resolution', 'Case resolution')], max_length=32)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], max_length=16)),
                ('subject_version', models.PositiveIntegerField(help_text="The subject's version at decision time; a stale value is refused.")),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_made', to='organizations.membership')),
                ('exception_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='exceptions.exceptioncase')),
                ('financial_recovery_item', models.ForeignKey(help_text='The only approval subject reachable in the Route B slice.', on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='exceptions.financialrecoveryitem')),
                ('financial_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='exceptions.financialimpactsnapshot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_revoked', to='organizations.membership')),
            ],
            options={
                'db_table': 'recovery_approval',
                'ordering': ['-decided_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('decision', 'approved'), ('revoked_at__isnull', True)), fields=('financial_recovery_item', 'approval_type'), name='uniq_live_approval_per_subject_type'), models.CheckConstraint(condition=models.Q(models.Q(('decision', 'revoked'), _negated=True), ('revoked_at__isnull', False), _connector='OR'), name='ck_revoked_approval_has_timestamp'), models.CheckConstraint(condition=models.Q(models.Q(('approval_type', 'invoice_ready'), ('decision', 'approved'), _negated=True), ('financial_snapshot__isnull', False), _connector='OR'), name='ck_invoice_ready_approval_names_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='FinanceExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(help_text='Stable hash of the exported item set and their approvals.', max_length=64)),
                ('content_sha256', models.CharField(max_length=64)),
                ('content', models.TextField(help_text='The generated CSV. Regenerating never changes it.')),
                ('row_count', models.PositiveIntegerField()),
                ('total_invoice_ready_value', models.DecimalField(decimal_places=4, help_text='Sum of the exported invoice-ready values ONLY. Never a cross-stage total.', max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('superseded_note', models.CharField(blank=True, help_text='Set when a source correction arrived after export. The export is retained.', max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_exports', to='organizations.membership')),
                ('items', models.ManyToManyField(blank=True, related_name='exports', to='exceptions.financialrecoveryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'recovery_finance_export',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_finance_export_idempotency'), models.CheckConstraint(condition=models.Q(('total_invoice_ready_value__gte', 0)), name='ck_export_total_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='FinancialStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('workflow', 'Workflow state change'), ('accounting', 'Accounting stage change'), ('dispute', 'Dispute opened or resolved')], max_length=16)),
                ('from_value', models.CharField(blank=True, max_length=32)),
                ('to_value', models.CharField(max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor_rule', models.CharField(blank=True, max_length=96)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_events', to='organizations.membership')),
                ('financial_recovery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='exceptions.financialrecoveryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_events', to='operations.accountinginvoice')),
            ],
            options={
                'db_table': 'recovery_financial_stage_event',
                'ordering': ['occurred_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor_membership__isnull', False), ('actor_rule', '')), models.Q(('actor_membership__isnull', True), models.Q(('actor_rule', ''), _negated=True)), _connector='OR'), name='ck_stage_event_exactly_one_actor')],
            },
        ),
    ]
