# Generated by Django 5.2.17 on 2026-08-27 18:45

import apps.common.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField(help_text='Site-local calendar date used in reconciliation.')),
                ('invoice_reference', models.CharField(max_length=128)),
                ('invoice_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('invoiced_at', models.DateTimeField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source_status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void'), ('disputed', 'Disputed')], max_length=16)),
                ('source_as_of_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'operations_accounting_invoice',
                'ordering': ['-invoiced_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(max_length=128)),
                ('collected_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('collected_at', models.DateTimeField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source_status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed'), ('disputed', 'Disputed')], max_length=16)),
                ('source_as_of_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'operations_accounting_payment',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended')], default='active', max_length=16)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('contract_reference', models.CharField(blank=True, help_text='Safe reference. Never upload a real contract.', max_length=64)),
            ],
            options={
                'db_table': 'operations_contract',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='ContractSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operations_contract_site',
                'ordering': ['site__name', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended')], default='active', max_length=16)),
                ('account_reference', models.CharField(blank=True, help_text='Safe internal reference. Never a credential.', max_length=64)),
            ],
            options={
                'db_table': 'operations_customer_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('service_type', models.CharField(help_text='Customer-defined controlled code.', max_length=64)),
                ('scope_kind', models.CharField(choices=[('base_recurring', 'Base recurring'), ('authorized_extra', 'Authorized extra'), ('periodic', 'Periodic'), ('corrective', 'Corrective')], max_length=24)),
                ('service_window_start', models.TimeField()),
                ('service_window_end', models.TimeField()),
                ('service_weekdays', models.CharField(help_text="Comma-separated weekday codes, e.g. 'mon,tue,wed'. Explicit, never inferred.", max_length=32)),
                ('role_code', models.CharField(max_length=64)),
                ('required_coverage_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('substitution_required_when_below_count', models.BooleanField()),
                ('billing_basis', models.CharField(choices=[('included', 'Included in base contract'), ('fixed_work_order', 'Fixed amount per work order'), ('hourly_actual', 'Hourly on actual hours'), ('hourly_scheduled', 'Hourly on scheduled hours'), ('manual_review', 'Manual review required')], max_length=24)),
                ('default_bill_rate', models.DecimalField(blank=True, decimal_places=4, help_text='NULL means unknown, never zero (section 18).', max_digits=12, null=True)),
                ('extra_work_requires_authorization', models.BooleanField()),
                ('uninvoiced_delay_days', models.PositiveIntegerField(help_text='Days after completion before unbilled work becomes a candidate.')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'operations_service_obligation',
                'ordering': ['contract_site', 'code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(help_text='IANA timezone. Used to convert instants to site-local service dates.', max_length=64, validators=[apps.common.validators.validate_iana_timezone])),
                ('region_code', models.CharField(blank=True, help_text='Coarse operational region, never a home address.', max_length=32)),
                ('site_type', models.CharField(choices=[('office', 'Office'), ('retail', 'Retail'), ('light_industrial', 'Light industrial'), ('other', 'Other')], default='office', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended')], default='active', max_length=16)),
            ],
            options={
                'db_table': 'operations_site',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Safe scope summary. Synthetic in demo.', max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('void', 'Void')], default='open', max_length=16)),
                ('billable', models.BooleanField()),
                ('authorization_required', models.BooleanField(default=False)),
                ('authorization_reference', models.CharField(blank=True, max_length=128)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('billing_basis', models.CharField(blank=True, choices=[('included', 'Included in base contract'), ('fixed_work_order', 'Fixed amount per work order'), ('hourly_actual', 'Hourly on actual hours'), ('hourly_scheduled', 'Hourly on scheduled hours'), ('manual_review', 'Manual review required')], max_length=24)),
                ('approved_fixed_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('approved_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source_as_of_at', models.DateTimeField(help_text='Freshness of the observing source.')),
            ],
            options={
                'db_table': 'operations_work_order',
                'ordering': ['-completed_at', '-scheduled_at'],
            },
        ),
    ]
