# Generated by Django 5.2.17 on 2026-08-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0002_organization_membership_membershiprolegrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinginvoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='accountingpayment',
            name='accounting_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.accountinginvoice'),
        ),
        migrations.AddField(
            model_name='accountingpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contractsite',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_sites', to='operations.contract'),
        ),
        migrations.AddField(
            model_name='contractsite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='operations.customeraccount'),
        ),
        migrations.AddField(
            model_name='accountinginvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_invoices', to='operations.customeraccount'),
        ),
        migrations.AddField(
            model_name='serviceobligation',
            name='contract_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_obligations', to='operations.contractsite'),
        ),
        migrations.AddField(
            model_name='serviceobligation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='site',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='operations.customeraccount'),
        ),
        migrations.AddField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contractsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_sites', to='operations.site'),
        ),
        migrations.AddField(
            model_name='accountinginvoice',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_invoices', to='operations.site'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='operations.contract'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='operations.customeraccount'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='operations.serviceobligation'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='operations.site'),
        ),
        migrations.AddField(
            model_name='accountinginvoice',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Set only when a confirmed mapping resolves to exactly one work order.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_invoices', to='operations.workorder'),
        ),
        migrations.AddConstraint(
            model_name='accountingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('collected_amount__gte', 0)), name='ck_payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_customer_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='ck_contract_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='serviceobligation',
            constraint=models.UniqueConstraint(fields=('organization', 'contract_site', 'code', 'effective_from'), name='uniq_obligation_per_site_code_effective'),
        ),
        migrations.AddConstraint(
            model_name='serviceobligation',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_obligation_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='serviceobligation',
            constraint=models.CheckConstraint(condition=models.Q(('required_coverage_count__gte', 1)), name='ck_obligation_coverage_positive'),
        ),
        migrations.AddConstraint(
            model_name='serviceobligation',
            constraint=models.CheckConstraint(condition=models.Q(('uninvoiced_delay_days__lte', 365)), name='ck_obligation_delay_within_year'),
        ),
        migrations.AddConstraint(
            model_name='serviceobligation',
            constraint=models.CheckConstraint(condition=models.Q(('default_bill_rate__isnull', True), ('default_bill_rate__gte', 0), _connector='OR'), name='ck_obligation_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_site_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contractsite',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_contract_site_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='contractsite',
            constraint=models.UniqueConstraint(fields=('organization', 'contract', 'site', 'effective_from'), name='uniq_contract_site_effective_from'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('approved_fixed_amount__isnull', True), ('approved_fixed_amount__gte', 0), _connector='OR'), name='ck_work_order_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('approved_hours__isnull', True), ('approved_hours__gte', 0), _connector='OR'), name='ck_work_order_hours_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('bill_rate__isnull', True), ('bill_rate__gte', 0), _connector='OR'), name='ck_work_order_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='ck_work_order_completed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='accountinginvoice',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_amount__gte', 0)), name='ck_invoice_amount_non_negative'),
        ),
    ]
