# Generated by Django 5.2.17 on 2026-08-27 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_membership_membershiprolegrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.UUIDField()),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_kind', models.CharField(choices=[('membership', 'Member'), ('worker', 'Worker'), ('detector', 'Detector'), ('system', 'System')], max_length=16)),
                ('actor_worker_id', models.UUIDField(blank=True, null=True)),
                ('actor_rule', models.CharField(blank=True, help_text='Detector/job identity for non-human actors.', max_length=96)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', 'object_type', 'object_id'], name='idx_audit_object'), models.Index(fields=['organization', 'actor_membership'], name='idx_audit_actor')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor_kind', 'membership'), ('actor_membership__isnull', False), ('actor_worker_id__isnull', True)), models.Q(('actor_kind', 'worker'), ('actor_worker_id__isnull', False), ('actor_membership__isnull', True)), models.Q(('actor_kind__in', ['detector', 'system']), ('actor_membership__isnull', True), ('actor_worker_id__isnull', True), models.Q(('actor_rule', ''), _negated=True)), _connector='OR'), name='ck_audit_exactly_one_actor')],
            },
        ),
    ]
