# Generated by Django 5.2.17 on 2026-08-27 18:45

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('default_timezone', models.CharField(default='America/New_York', help_text='IANA timezone used for organization-wide reporting.', max_length=64, validators=[apps.common.validators.validate_iana_timezone])),
                ('currency', models.CharField(choices=[('USD', 'US dollar')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=16)),
                ('demo_mode', models.BooleanField(default=False, help_text='Synthetic labelling only. Never an authentication or validation bypass.')),
            ],
            options={
                'db_table': 'organizations_organization',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null only for the bootstrap owner (section 22.2).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_membership',
                'ordering': ['organization__display_name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRoleGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Organization owner'), ('operations_manager', 'Operations manager'), ('supervisor', 'Site supervisor'), ('finance_reviewer', 'Finance reviewer'), ('auditor', 'Auditor / read-only')], max_length=32)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_grants_made', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='organizations.membership')),
            ],
            options={
                'db_table': 'organizations_membership_role_grant',
                'ordering': ['membership', 'role'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('membership', 'role'), name='uniq_active_role_grant_per_membership')],
            },
        ),
        migrations.CreateModel(
            name='MembershipSiteGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_grants_made', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_grants', to='organizations.membership')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_grants', to='operations.site')),
            ],
            options={
                'db_table': 'organizations_membership_site_grant',
                'ordering': ['membership', 'site'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'site'), name='uniq_site_grant_per_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='uniq_membership_org_user'),
        ),
    ]
